spring.application.name=autocare-main

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/autocare_main_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=yettel123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true